alias tmux="env TERM=screen-256color-bce tmux"

alias ga='git add'
alias gaa='git add -A'
alias gb='git branch'
alias gbd='git branch -D'
alias gco='git commit -m'
alias gcoa='git commit -a -m'
alias gch='git checkout'
alias gchb='git checkout -b'
alias gd='git diff'
alias gdc='git diff --cached'
alias gdv='git diff | vim -'
alias gdcv='git diff --cached | vim -'
alias gf='git fetch'
alias gl='git log'
alias gpl='git rev-parse --abbrev-ref HEAD | xargs git pull origin'
alias gps='git rev-parse --abbrev-ref HEAD | xargs git push origin'
alias gr='git reset'
alias gss='git stash'
alias gssl='git stash list'
alias gssp='git stash pop'
alias gst='git status'

